name: lee-gyu/bff-apps

services:
    db-postgres:
        image: postgres:16
        restart: always
        volumes:
            - bff-apps-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: PG_PASSWORD_HERE
    pg-admin:
        image: dpage/pgadmin4
        restart: always
        links:
            - db-postgres:postgres
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: default@example.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin4
        volumes:
            - bff-apps-pg-admin:/var/lib/pgadmin

volumes:
    bff-apps-db-data:
    bff-apps-pg-admin:
