name: lee-gyu/bff-monorepo

services:
    db-postgres:
        image: postgres:16
        restart: always
        ports:
            - 5432:5432
        volumes:
            - bff-apps-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "${PG_USER}"
            POSTGRES_PASSWORD: "${PG_PASSWORD}"
    pg-admin:
        image: dpage/pgadmin4
        restart: always
        links:
            - db-postgres:postgres
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PWD}"
        volumes:
            - bff-apps-pg-admin:/var/lib/pgadmin

volumes:
    bff-apps-db-data:
    bff-apps-pg-admin:
